apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.nodePort }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      port: {{ .Values.service.port }}
  selector:
    {{- include "webapp.selectorLabels" . | nindent 4 }}
